---

  - name: 5.1.1 Install the rsyslog package (Scored)
    apt: name=rsyslog state=present

  - name: 5.1.2 Activate the rsyslog Service (Scored)
    service: name=rsyslog enabled=yes state=started

  - name: 5.1.3 Configure /etc/rsyslog.conf (Not Scored)
    copy: >
      src=etc/rsyslog.conf
      dest=/etc/rsyslog.conf
      owner=root
      group=root
      mode=0644

  - name: 5.1.4 Create and Set Permissions on rsyslog Log Files (Scored)
    file: >
      path=/var/log/{{ item }}
      state=touch
      owner=root
      group=wheel
      mode=0640
    with_items:
        - messages
        - kern.log
        - daemon.log
        - syslog
        - unused.log
